# Theme metadata
name = "Minimal"

# Is theme light or dark?
light = true

# Primary
primary = "#1565c0"

# Menu
menu_primary = "#3f51b5"
menu_text = "#f5f5f5"
menu_text_active = "#fff"
menu_title = "#fff"

# Home sections
home_section_odd = "rgb(255, 255, 255)"
home_section_even = "rgb(247, 247, 247)"

[dark]
  link = "#bbdefb"
  link_hover = "#bbdefb"
